# Generated by Django 2.2.4 on 2019-08-29 21:49

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ratings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='images/', location='/images/'), upload_to=ratings.models.image_directory_path)),
                ('price', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Bad'), (2, 'Dislike'), (3, 'OK'), (4, 'Like'), (5, 'Love')])),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Dress')),
            ],
        ),
    ]
