# Generated by Django 2.2.4 on 2019-09-03 14:45

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import ratings.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('image', models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location='/Users/pallavisibia/Desktop/my_projects/traint/media//images/'), upload_to=ratings.models.image_directory_path)),
                ('price', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, 'Bad'), (2, 'Dislike'), (3, 'OK'), (4, 'Like'), (5, 'Love')])),
                ('user_name', models.CharField(max_length=100)),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.Dress')),
            ],
        ),
    ]
