# Generated by Django 2.2.4 on 2019-09-01 21:33

import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone
import ratings.models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dress',
            name='image',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location='/Users/pallavisibia/Desktop/my_projects/traint/media//images/'), upload_to=ratings.models.image_directory_path),
        ),
    ]
